// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using homework.Models;

namespace homework.Migrations
{
    [DbContext(typeof(ShopingContext))]
    [Migration("20181123122855_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("homework.Models.Member", b =>
                {
                    b.Property<string>("UId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UName");

                    b.Property<string>("UPwd");

                    b.HasKey("UId");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
