// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using homework.Models;

namespace homework.Migrations
{
    [DbContext(typeof(ShopingContext))]
    [Migration("20181209155945_init5")]
    partial class init5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("homework.Models.Admin", b =>
                {
                    b.Property<string>("Account")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.HasKey("Account");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("homework.Models.Member", b =>
                {
                    b.Property<string>("UId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UName");

                    b.Property<string>("UPwd");

                    b.HasKey("UId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("homework.Models.Order", b =>
                {
                    b.Property<string>("OId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MembersUId");

                    b.Property<string>("PruductIDPId");

                    b.Property<int>("orderQty");

                    b.HasKey("OId");

                    b.HasIndex("MembersUId");

                    b.HasIndex("PruductIDPId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("homework.Models.Pruduct", b =>
                {
                    b.Property<string>("PId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PName");

                    b.Property<int>("Price");

                    b.Property<int>("Qty");

                    b.HasKey("PId");

                    b.ToTable("Pruducts");
                });

            modelBuilder.Entity("homework.Models.Order", b =>
                {
                    b.HasOne("homework.Models.Member", "Members")
                        .WithMany()
                        .HasForeignKey("MembersUId");

                    b.HasOne("homework.Models.Pruduct", "PruductID")
                        .WithMany()
                        .HasForeignKey("PruductIDPId");
                });
#pragma warning restore 612, 618
        }
    }
}
